
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Mar 02 18:25:30 CST 2015
//----------------------------------------------------

package com.norllanac.compiladores2018.Models.ejemploHTML;

/** CUP generated class containing symbol constants. */
public class Simbolo {
  /* terminals */
  public static final int ftitle = 5;
  public static final int palabra = 13;
  public static final int ihtml = 2;
  public static final int ibody = 8;
  public static final int EOF = 0;
  public static final int ih1 = 10;
  public static final int numero = 12;
  public static final int ihead = 6;
  public static final int fhtml = 3;
  public static final int fbody = 9;
  public static final int error = 1;
  public static final int fh1 = 11;
  public static final int fhead = 7;
  public static final int ititle = 4;
}

